version: '3.8'

services:
  web_app:  # Сервис для Flask-приложения
    container_name: web_app
    build: .
    ports:
      - "5000:5000"  # Проброс порта для приложения
    volumes:
      - .:/app  # Связывание текущей директории с директориeй в контейнере
    depends_on:
      - mongo_container  # Указываем зависимость от контейнера с MongoDB
  mongo_container:  # Сервис для MongoDB
    container_name: mongo_container
    image: mongo  # Используем официальный образ MongoDB
    ports:
      - "27023:27017"  # Проброс порта для MongoDB

networks:
  default:
    external:
      name: my_bridge_network